title: Tracking My GitHub Learning
author: msm
email: msm@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'll use this GitHub-hosted site comprising static web content to 
  track my progress thru various GitHub course offerings.

# social links
twitter_username: i-forgot
github_username:  markm445

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
